Sunset svn git access
ESMCI/manage_externals pull request #205
Opened 2023-11-16 00:08 UTC by jedwards4b

Remove support for svn access to github

User interface changes?:  Yes
github no longer supports svn access

Fixes: 

Testing:
  test removed: test of svn access to github. tests of submodules
                          We still use submodules and should test them but due to
                            fatal: transport 'file' not allowed  our local test doesn't work and
                            I haven't figured out how to replace.

  unit tests: all pass 
  system tests: all pass
  manual testing:

2023-11-16 08:37 UTC, gold2718 requested changes
Remove commented code?

2023-11-16 08:37 UTC, gold2718 commented on test/test_sys_checkout.py
> +    # def test_submodule_checkout_bare(self):
Why is this commented out? It is not being used and if we ever need it, we can recall it (it helps to mention that it is removed in the log message).

2023-11-16 12:37 UTC, jedwards4b commented on test/test_sys_checkout.py
> +    # def test_submodule_checkout_bare(self):
It's commented out because of [this issue](https://vielmetti.typepad.com/logbook/2022/10/git-security-fixes-lead-to-fatal-transport-file-not-allowed-error-in-ci-systems-cve-2022-39253.html).  I have been unable to find a suitable fix but am still trying, if you have a suggestion that would allow these tests to pass please provide.    This is issue #202

2023-11-16 13:48 UTC, jedwards4b commented on test/test_sys_checkout.py
> +    # def test_submodule_checkout_bare(self):
@gold2718 I figured it out, all tests now pass.

2023-11-16 18:59 UTC, billsacks commented
@jedwards4b - thank you very much for your quick work to resolve these issues!

I see that you removed some system tests of the svn protocol. I'm guessing you did that because they were set up to use the svn protocol to access a GitHub repo. I haven't looked closely at the tests, but I'm wondering if we can switch them to access an actual svn repo so that we can keep these tests in place. For example, cgd still maintains an svn server (which I'm embarrassed to admit that I still use for some personal repos that I've never bothered to switch over to git)... we could set up a little test repository there. If this makes sense to you, I could take a stab at it.

2023-11-16 19:02 UTC, jedwards4b commented
I looked at that test and thought that it was specific to svn access to git, I assumed that there were other tests for svn but to be honest I didn't look carefully.  I was really more concerned about the submodule testing which I finally managed to fix.

2023-11-16 20:19 UTC, billsacks commented
Okay, let me see if I can get this working with an actual svn repo. I'm going to try using a little local test repo that we can access with the `file://` protocol. It's been a long time since I've done svn repo administration, but I think I've figured out the essential parts, so let me see if I can get it working....

2023-11-16 20:32 UTC, gold2718 reviewed
Don't feel great about magic security strings in the mainline code.

2023-11-16 20:32 UTC, gold2718 commented on manic/repository_git.py
> +        if "test/tmp/test_submodule" in dirname:
Having this in the main code feels like a security hole waiting to cause trouble.
```
mkdir -p test/temp/test_submodule && cd test/temp/submodule
git clone . . . 
```
At this point, can't I call into this method with a `dirname` that matches this 'magic' pattern?
Instead of hardcoding this magic pattern into the mainline manic code, is it possible to set this flag inside the GitHub CI so that it is active when the test of this method runs?

2023-11-16 20:38 UTC, jedwards4b commented on manic/repository_git.py
> +        if "test/tmp/test_submodule" in dirname:
I am happy to consider your alternate proposal.  I spent an inordinate amount of time to come up with this solution, but I certainly don't want to introduce any security issues.   If you feel that the security risk is greater than the risk of not testing this then we should go back to just removing these tests.   It's not just the github CI that fails without this change - the tests fail when you run make stest on your local system as well.

2023-11-16 21:21 UTC, jedwards4b commented on manic/repository_git.py
> +        if "test/tmp/test_submodule" in dirname:
I'm happy to consider other ways to figure out if I am in a test context and should thus apply the file_protocol while in 
_git_update_submodules.  

Would it be preferable to pass an optional variable testing=True all the way down the stack?  It's 6 or 7 layers deep.

2023-11-16 21:30 UTC, jedwards4b commented on manic/repository_git.py
> +        if "test/tmp/test_submodule" in dirname:
@gold2718 How about now?

2023-11-16 21:31 UTC, billsacks commented on manic/repository_git.py
> +        if "test/tmp/test_submodule" in dirname:
One other possible idea: instead of making file_protocol a local variable, make it a function (or a method of the GitRepository class). Its implementation in production code will be to just return an empty string. In unit tests, we could use mocking to replace it with a function that returns this special string.

Oh, I see you just pushed a new change... I'm okay with that solution, too.

2023-11-16 21:41 UTC, billsacks commented
@jedwards4b - see #206 for a fix to the svn-based sys tests. If that looks reasonable to you, can you please back out most of your changes in test_sys_checkout.py – other than the last two lines of changes, which change the git submodule commands – and then merge my changes in #206 into this branch (we can either merge them to main and you can update this branch to main, or you could merge my branch directly into this branch).

2023-11-16 23:20 UTC, billsacks approved these changes
Awesome, looks good - thanks @jedwards4b !

2023-11-17 15:07 UTC, jedwards4b commented
@gold2718 have you looked at this new solution?  Do you still have concerns?

2023-11-17 15:31 UTC, gold2718 commented
> @gold2718 have you looked at this new solution? Do you still have concerns?

Sorry, been in meetings. Will grab a look now

2023-11-17 15:42 UTC, gold2718 approved these changes
Looks good now, thanks!

2023-11-17 15:42 UTC, gold2718 commented on manic/repository_git.py
> +        if 'unittest' in sys.modules.keys():
Nice! Not perfect but more than enough of a cross check for this sort of application.

2023-11-17 15:55 UTC, merged