add a components arg to checkout only select components
ESMCI/manage_externals pull request #83
Opened 2018-03-29 17:05 UTC by jedwards4b

Add optional argument to only process components listed on the command line
checkout_externals cam clm 
will only process externals associated with the listed components cam and clm.

User interface changes?: Yes 
An additional command line option was added, previous functionality continues to be supported 

Fixes: #80 

Testing: 
  test removed:
  unit tests:  all pass
  system tests:
  manual testing:  Tested with lists of components in Externals.cfg and with ones that were not there.

2018-04-03 20:52 UTC, billsacks commented
I haven't been following the optional components design discussion, so I'm adding @gold2718 as a reviewer instead of myself.

@jedwards4b it appears that many of the system tests are failing. Let me know if you'd like a bit of an orientation to the manage_externals testing, if you haven't used it before.

2018-04-03 21:01 UTC, jedwards4b commented
@billsacks yes, I would appreciate that.  I ran them from the command line and all passed.

2018-04-03 22:07 UTC, jedwards4b commented
@billsacks All of these tests fail on master as well.

2018-04-03 22:11 UTC, jedwards4b commented
Sorry that last was incorrect,  all tests pass on master and on my branch:
```
make utest
PYTHONPATH=..: python -m unittest discover --buffer --pattern 'test_unit_*.py'
........................................................................................................................................
----------------------------------------------------------------------
Ran 136 tests in 0.118s

OK
(env_python2) cheyenne3: /glade/p/work/jedwards/sandboxes/manage_externals/test
:) git branch
* jedwards/components_arg
  master
(env_python2) cheyenne3: /glade/p/work/jedwards/sandboxes/manage_externals/test
```

2018-04-03 22:49 UTC, billsacks commented
@jedwards4b the issue is that there are other tests besides `make utest`: try `make stest` for the system tests, or just `make test` (the latter does utest & stest).

2018-04-04 00:54 UTC, jedwards4b commented
@billsacks testing now passes - what's with the coverage check?

2018-04-04 01:04 UTC, billsacks commented
Thanks, @jedwards4b . I'm happy with this once @gold2718 gives his okay.

@bandre-ucar added an automated code coverage check, which I think checks the coverage of all of the unit and system tests. I guess this is telling us that (much of) the new code isn't covered by any unit or system tests, hence the decrease in code coverage. I guess that, ideally, there would be a test added to cover this new code; I'm fine leaving it to you to determine whether it's worth doing so, based on (a) how critical this code is, and (b) how hard it would be to add tests for it.

2018-04-04 03:04 UTC, jedwards4b commented
someone who knew the format of these tests could do this in no time, but I have to blunder my way through.  This is really nicely written and documented code, it's too bad the help desk is so unresponsive.

2018-04-04 11:07 UTC, billsacks commented
@jedwards4b great, thanks for adding those tests.

2018-04-04 12:33 UTC, jedwards4b commented
I don't know what I need to do to improve the coverage further.

2018-04-04 13:02 UTC, billsacks commented
It seems normal for coverage to vary up or down by small amounts like this, and I think @bandre-ucar has been accepting changes even for small decreases in coverage. So I don't think you need to do anything more. (Aside: I wonder if there's a way to configure coveralls to list it as passing as long as coverage doesn't decrease by more than ~ 1% or so - or maybe just make that informational rather than a failing check.)

2018-04-10 15:51 UTC, gold2718 requested changes
Mostly good but one show stopper for CAM moving forward.

2018-04-10 15:51 UTC, gold2718 commented on manic/checkout.py
> +    if args.optional or args.components:
It seems to me that if you use the new interface to specify a component (e.g., cam), this will force CAM to load all of its optional components which is certainly _not_ the correct behavior. Is there a reason this has to be there?

2018-04-10 15:51 UTC, gold2718 commented on manic/checkout.py
> +            for comp in args.components:
I know this does the right thing but I feel adding an else before the loop would clarify that only one of these actions is intended to be taken.

2018-04-10 15:51 UTC, gold2718 commented on manic/externals_description.py
>          """Convert the xml into a standardized dict that can be used to
If we are here, aren't we cfg format situation? If so, please fix this comment.

2018-04-10 15:51 UTC, gold2718 commented on test/test_sys_checkout.py
> +
This is a good test but it seems that adding tests is not part of our standard PR template. Still, adding a mention of the new test is a good idea (IMHO).

2018-04-10 17:06 UTC, jedwards4b commented on manic/checkout.py
> +            for comp in args.components:
Actually I originally had it that way and pylint flagged it as "too many branches."

2018-04-10 17:07 UTC, jedwards4b commented on manic/checkout.py
> +    if args.optional or args.components:
Good point - I'll need to think about this a bit.

2018-04-10 17:11 UTC, gold2718 commented on manic/checkout.py
> +            for comp in args.components:
pylint needs to get a life 👎  (but okay to leave it as is).

2018-04-10 18:14 UTC, gold2718 commented
@jedwards4b, will this new feature work if you have a dirty sandbox in an non-involved component? For instance, say components/pop is modified, can
```
./manage_externals/checkout_externals FMS
```
still work?

2018-04-10 20:21 UTC, jedwards4b commented
@gold2718 I think that I've addressed all of your concerns.   Thanks

2018-04-10 20:30 UTC, jedwards4b commented
The answer to your dirty sandbox question is yes, sandboxes not directly involved in the request are ignored.

2018-04-10 20:41 UTC, gold2718 approved these changes

2018-04-10 21:22 UTC, merged

2018-04-10 21:24 UTC, billsacks commented
@jedwards4b - I have merged this. Ben was making a tag for each merge to master, I think. Any feelings on whether we should continue that practice?

2018-04-10 21:26 UTC, gold2718 commented
I am fine with fewer tags.

2018-04-10 21:31 UTC, jedwards4b commented
I don't see a strong need for tags.